[package]
name = "forge-attractor"
version = "0.1.0"
edition = "2024"

[dependencies]
graphviz-rust = { version = "0.9.6", default-features = false }
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
serde_json = "1"
